name: Deploy WordPress to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Railway
        run: echo "${{ ddfa14d7-7105-4b4d-8035-7f5e8c5250d0.RAILWAYAPIKEY }}" | railway login --ci

      - name: Deploy to Railway
        run: railway up --service wordpress
